use_frameworks!

target 'Socket.swift_Example' do
  pod 'Socket.swift', :path => '../'

  target 'Socket.swift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
